### ISSUE TITLE
Running with cmake, csbuild needs to wrap the c complier which is cached

### ISSUE THREAD

**Issue by cryptomilk** [kdudka/csmock#13]
Running with cmake, csbuild needs to wrap the c complier which is cached.

The --pre-cmd should allow to specify the cmake command. Maybe add an option --build-dir which will be removed if needed!

**Comment by kdudka** [comment]
True.  We should also make sure that results of out of tree builds pass through the default filters.

**Comment by cryptomilk** [comment]
Well, you could check the CMakeCache.txt file for the compiler path and if it is not pointing to cscppc then print the instruction how to run cmake cmake correctly ...

**Comment by kdudka** [comment]
Thanks for the suggestion!  Improvements addressing both the issues are now implemented as PR #16.

**Comment by cryptomilk** [comment]
I'm back at work on Monday.

However I have a question, how do you switch between csclng and cscppc? Becaue you need to run cmake configure for that as it caches the compiler path.

**Comment by kdudka** [comment]
We do not switch really.  All the wrappers (cscppc, csclng, cswrap) get chained in `$PATH`, depending on the availability of the tools.  Each of the wrappers just removes itself from `$PATH` and calls the next one.  This usually works fully transparently if compiler is invoked by its base name, which autotools-based projects usually do.

The approach is not very different from what `ccache` or `distcc` do.  If you run `cmake` without having the wrappers in `$PATH`, subsequent run of `make` would ignore any changes to `$PATH` that would otherwise enable the wrappers.

We just need to make sure that `cmake` already runs with the updated `$PATH`, which both `--prep-cmd` and `--build-cmd` do with this fix.  If user runs `cmake` before running `csbuild`, the scan should fail with the suggested error message in the most common cases now.
