### ISSUE TITLE
Add a --builddir option to let csbuild take care of managing the directory.

### ISSUE THREAD

**Issue by cryptomilk** [kdudka/csmock#17]
csbuld should provide a --builddir argument for managing the build directory. It should take take of removing and creating it if required and then run the pre-cmd and build cmd in there.

If build dir is not an absolute path then your should join it with the source directory:

    srcdir/builddir 

Adding this it might be useful you have a vairable for the source dir which csbuild will replace e.g.

`--builddir=obj --pre-cmd "cmake @SRCDIR@"` or whatever you prefer :-)

**Comment by kdudka** [comment]
Thanks for the suggestion!  Just few remarks:

- I propose to spell it `--build-dir` to keep the naming consistent with all the existing option names.
- Should we require the specified directory not to exist when csbuild is invoked?  Otherwise, it would have fatal consequences if the option was used incorrectly.  For example, if user confused source and build directories, csbuild could permanently delete hours of work.  This could be probably mitigated by searching for the `.git` directory before wiping the build directory.
- Should `@SRCDIR@` be always set to `$PWD` at the time of csbuild invocation?  Or should we provide equivalent `--src-dir` option?  We could probably start with the former and postpone implementation of the latter till someone actually requests it.

**Comment by cryptomilk** [comment]
* --build-dir sounds good
* Yes, I think if you run csbuild and -build-dir exists, we should fail. We should not delete existing directories.
* Yes, just set @SRCDIR@ do $PWD, if needed --src-dir could be added later.

**Comment by cryptomilk** [comment]
Good idea!

**Comment by kdudka** [comment]
@cryptomilk Could you please try out the following copr build?
https://copr.fedorainfracloud.org/coprs/kdudka/csmock-testing/build/811751/

**Comment by cryptomilk** [comment]
This works just perfectly for me. Thanks for your work!
