### ISSUE TITLE
csbuild fails when run in in a gitlab CI container

### ISSUE THREAD

**Issue by cryptomilk** [kdudka/csmock#20]
csbuild fails with the following error:

```
/usr/share/csbuild/scripts/run-scan.sh: error: /builds/cryptomilk/libssh-mirror/obj-csbuild/CMakeCache.txt contains 'CMAKE_C_COMPILER=/usr/lib64/cscppc/cc' instead of 'CMAKE_C_COMPILER=', which is required to wrap the compiler.  Please run cmake through csbuild to fix this.
```

The path in the cache looks correct, but the expected check seems to be wrong as it is empty.

**Comment by kdudka** [comment]
This must be caused by `which` utility not being available in that container.  I am not sure if there is a portable way to fix this.  Ideally we would use a shell built-in but there is no such built-in that would work in all commonly used shells.  In ksh/zsh we could use `whence $rel_path` but it does not work in bash.  In bash we could use something like `hash $rel_path && hash -t $rel_path` but it does not work in ksh/zsh.

**Comment by cryptomilk** [comment]
What about `type` if `which` fails?

**Comment by cryptomilk** [comment]
Or `command -p -v`

**Comment by kdudka** [comment]
Thanks for the suggestion!  `command -v $rel_path` seems to do the job for us in a (more) portable way.  Proposed as PR #21.
