### ISSUE TITLE
csmock not support Coverity now?

### ISSUE THREAD

**Issue by Ranler** [kdudka/csmock#23]
There are no Coverity plugin as `csmock --list-available-tools` output, so Coverity are not supoort now for `csmock` command ?
Thanks.

**Comment by kdudka** [comment]
This repository contains plug-ins for open source static analyzers only.  We use a csmock plug-in for Coverity internally at Red Hat.  However, it is not much useful externally because it depends on local installation of proprietary software.

**Comment by Ranler** [comment]
Thanks. Its weird that `csbuild` could call Coverity command.

**Comment by kdudka** [comment]
Yes, `csbuild` just invokes `cov-build`, `cov-analyze` and `cov-format-errors` if they are found in `$PATH`.  The use of Coverity in `csmock` is, however, more advanced because it needs copy certain parts of the local Coverity installation into mock's chroot etc.

This reminds me that we should change `csbuild` to use the JSON output of `cov-format-errors` instead of `--emacs-style` to make it work with Coverity 2018.12.

**Comment by kdudka** [comment]
> This reminds me that we should change csbuild to use the JSON output of cov-format-errors instead of --emacs-style to make it work with Coverity 2018.12.

Pushed as 20f1668f6fb20eae6568b0f0c5538e64076c7085.

**Comment by amaslenn** [comment]
@kdudka are there any options to invoke Coverity in `csmock` if I have it installed in my setup? I don't see `coverity` plugin in the repo, do you have any plans to upstream it?

**Comment by kdudka** [comment]
> @kdudka are there any options to invoke Coverity in csmock if I have it installed in my setup?

Unless you are an employee of Red Hat, not really.

> I don't see coverity plugin in the repo, do you have any plans to upstream it?

Sorry, there are no plans to make the Coverity plug-in for csmock publicly available.  It is tightly integrated with the non-free software it depends on, which makes it complicated (or even impossible) legalwise.
