### ISSUE TITLE
csbuild doesn't print current, added and fixed

### ISSUE THREAD

**Issue by cryptomilk** [kdudka/csmock#9]
csbuild doesn't print current, added and fixed. See also your own build:

https://travis-ci.org/kdudka/cscppc/builds/406306254?utm_source=github_status&utm_medium=notification

**Comment by kdudka** [comment]
My original impression was that you complained about missing section headers when there were no potential bugs to report.  It turned out that you were actually complaining about unexpectedly empty results, which was caused by something else.  Do you think that #12 still makes sense or should we just drop it?

**Comment by cryptomilk** [comment]
I think it makes sense to print something if you request it with --print-<foo>

Then you know ok, nothing has found for this kind of result.

**Comment by kdudka** [comment]
Fair enough, merging...
